-- Tabela de funcionários
CREATE TABLE RH_FUNCIONARIOS (
    COD_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(100) NOT NULL
);

-- Layouts associados a uma layer
CREATE TABLE CI_LAYOUT (
    ID_CI_LAYOUT INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_LAYER INT,
    LAYOUT_NAME VARCHAR(100),
    DT_CREATION DATETIME,
    LAST_MODIFICATION DATETIME,
    DISPLAY_STATE BOOLEAN,
    DT_BEGIN_DISPLAY DATETIME,
    DT_END_DISPLAY DATETIME,
    NO_END_TIME BOOLEAN,
    ID_CI_LAYOUT_THEME INT,
    TYPE VARCHAR(100),
    FOREIGN KEY (ID_CI_LAYER) REFERENCES CI_LAYER(ID_CI_LAYER),
    FOREIGN KEY (ID_CI_LAYOUT_THEME) REFERENCES CI_LAYOUT_THEME(ID_CI_LAYOUT_THEME)
);

-- Temas visuais
CREATE TABLE CI_LAYOUT_THEME (
    ID_CI_LAYOUT_THEME INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    PRIMARY_TEXT_COLOR VARCHAR(20),
    SECONDARY_TEXT_COLOR VARCHAR(20),
    PRIMARY_BACKGROUND_COLOR VARCHAR(20),
    SECONDARY_BACKGROUND_COLOR VARCHAR(20),
    LIGHT_COLOR VARCHAR(20),
    CREATED_BY VARCHAR(255)
);

-- DISPLAY TYPE
CREATE TABLE CI_DISPLAY_TYPE (
    ID_CI_DISPLAY_TYPE INT AUTO_INCREMENT PRIMARY KEY,
    DISPLAY_NAME VARCHAR(100) NOT NULL,
    DISPLAY_ILLUSTRATION LONGBLOB NOT NULL,
    DISPLAY_COMPONENT_1 VARCHAR(30) NOT NULL,
    DISPLAY_COMPONENT_2 VARCHAR(30),
    DISPLAY_COMPONENT_3 VARCHAR(30),
    DISPLAY_COMPONENT_4 VARCHAR(30),
    DISPLAY_COMPONENT_5 VARCHAR(30),
    CREATED_BY VARCHAR(255)
);

-- Componente de texto
CREATE TABLE CI_COMPONENT_TEXT_BLOCK (
    ID_CI_COMPONENT_TEXT_BLOCK INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_LAYOUT INT,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT,
    FONT_SIZE VARCHAR(10),
    FONT_WEIGHT VARCHAR(20),
    FOREIGN KEY (ID_CI_LAYOUT) REFERENCES CI_LAYOUT(ID_CI_LAYOUT)
);

-- Componente de clima
CREATE TABLE CI_COMPONENT_WEATHER (
    ID_CI_COMPONENT_WEATHER INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_LAYOUT INT,
    STATE_REGION VARCHAR(100) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    UNIT VARCHAR(10),
    ID_CI_API_COMPONENTS INT,
    FOREIGN KEY (ID_CI_LAYOUT) REFERENCES CI_LAYOUT(ID_CI_LAYOUT)
    FOREIGN KEY (ID_CI_API_COMPONENTS) REFERENCES CI_API_COMPONENTS(ID_CI_API_COMPONENTS)
);

-- Componente de carrossel de imagens
CREATE TABLE CI_COMPONENT_IMAGE_CAROUSEL (
    ID_CI_COMPONENT_IMAGE_CAROUSEL INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_LAYOUT INT,
    DURATION_IMAGES INT NOT NULL,
    FOREIGN KEY (ID_CI_LAYOUT) REFERENCES CI_LAYOUT(ID_CI_LAYOUT)
);

-- Testo linkado com carrossel de imagens
CREATE TABLE CI_COMPONENT_IMAGE_CAROUSEL_TEXT (
    ID_CI_COMPONENT_IMAGE_CAROUSEL_TEXT INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_COMPONENT_IMAGE_CAROUSEL INT,
    CONTENT VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_CI_COMPONENT_IMAGE_CAROUSEL) REFERENCES CI_COMPONENT_IMAGE_CAROUSEL(ID_CI_COMPONENT_IMAGE_CAROUSEL)
);

-- Contrato de uso entre imagens e components
CREATE TABLE CI_USE_IMAGE (
    ID_CI_USE_IMAGE INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_COMPONENT_IMAGE_CAROUSEL INT,
    ID_CI_IMAGE INT,
    ORDER_INDEX INT NOT NULL,
    FOREIGN KEY (ID_CI_COMPONENT_IMAGE_CAROUSEL) REFERENCES CI_COMPONENT_IMAGE_CAROUSEL(ID_CI_COMPONENT_IMAGE_CAROUSEL),
    FOREIGN KEY (ID_CI_IMAGE) REFERENCES CI_IMAGE(ID_CI_IMAGE)
);

-- Imagens
CREATE TABLE CI_IMAGE (
    ID_CI_IMAGE INT AUTO_INCREMENT PRIMARY KEY,
    COD_FUNCIONARIO INT,
    IMAGE_ARCHIVE LONGBLOB NOT NULL,
    CAPTION VARCHAR(255),
    FOREIGN KEY (COD_FUNCIONARIO) REFERENCES RH_FUNCIONARIOS(COD_FUNCIONARIO)
);

-- Midias
CREATE TABLE CI_MIDIA (
    ID_CI_MIDIA INT AUTO_INCREMENT PRIMARY KEY,
    COD_FUNCIONARIO INT,
    MIDIA_ARCHIVE LONGBLOB NOT NULL,
    CAPTION VARCHAR(255),
    TYPE_OF_ARCHIVE VARCHAR(100), 
    FOREIGN KEY (COD_FUNCIONARIO) REFERENCES RH_FUNCIONARIOS(COD_FUNCIONARIO)
);

-- Componentes de API
CREATE TABLE CI_API_COMPONENTS (
    ID_CI_API_COMPONENTS INT AUTO_INCREMENT PRIMARY KEY,
    API_PROVIDER VARCHAR(255),
    API_DESCRIPTION VARCHAR(255),
    API_KEY VARCHAR(255),
    COMPATIBLE_COMPONENTS VARCHAR(10), 
    IS_ACTIVE BOOLEAN,
    CREATED_BY VARCHAR(255)
);