-- Tabela de funcionários
CREATE TABLE RH_FUNCIONARIOS (
    COD_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_FUNCIONARIO VARCHAR(100) NOT NULL
);

-- Camadas de posicionamento
CREATE TABLE CI_LAYER (
    ID_CI_LAYER INT AUTO_INCREMENT PRIMARY KEY,
    COD_FUNCIONARIO INT,
    WIDTH INT,
    HEIGHT INT,
    POSITION_X INT,
    POSITION_Y INT,
    Z_INDEX INT,
    FOREIGN KEY (COD_FUNCIONARIO) REFERENCES RH_FUNCIONARIOS(COD_FUNCIONARIO)
);

-- Layouts associados a uma layer
CREATE TABLE CI_LAYOUT (
    ID_CI_LAYOUT INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_LAYER INT,
    NAME VARCHAR(100),
    DT_CREATION DATETIME,
    LAST_MODIFICATION DATETIME,
    DISPLAY_STATE BOOLEAN,
    DT_BEGIN_DISPLAY DATETIME,
    DT_END_DISPLAY DATETIME,
    NO_END_TIME BOOLEAN,
    FOREIGN KEY (ID_CI_LAYER) REFERENCES CI_LAYER(ID_CI_LAYER)
);

-- Temas visuais
CREATE TABLE CI_LAYOUT_THEME (
    ID_CI_LAYOUT_THEME INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100),
    PRIMARY_TEXT_COLOR VARCHAR(20),
    SECONDARY_TEXT_COLOR VARCHAR(20),
    PRIMARY_BACKGROUND_COLOR VARCHAR(20),
    SECONDARY_BACKGROUND_COLOR VARCHAR(20),
    LIGHT_COLOR VARCHAR(20)
);

-- Tipos de layout que pertencem a um tema
CREATE TABLE CI_LAYOUT_TYPE (
    ID_CI_LAYOUT_TYPE INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_LAYOUT INT,
    ID_CI_LAYOUT_THEME INT,
    TYPE VARCHAR(100),
    FOREIGN KEY (ID_CI_LAYOUT) REFERENCES CI_LAYOUT(ID_CI_LAYOUT),
    FOREIGN KEY (ID_CI_LAYOUT_THEME) REFERENCES CI_LAYOUT_THEME(ID_CI_LAYOUT_THEME)
);

-- Componente de texto
CREATE TABLE CI_COMPONENT_TEXT_BLOCK (
    ID_CI_COMPONENT_TEXT_BLOCK INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_LAYOUT_TYPE INT,
    TITLE VARCHAR(255),
    CONTENT TEXT,
    FONT_SIZE VARCHAR(10),
    FONT_WEIGHT VARCHAR(20),
    FOREIGN KEY (ID_CI_LAYOUT_TYPE) REFERENCES CI_LAYOUT_TYPE(ID_CI_LAYOUT_TYPE)
);

-- Componente de clima
CREATE TABLE CI_COMPONENT_WEATHER (
    ID_CI_COMPONENT_WEATHER INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_LAYOUT_TYPE INT,
    CITY VARCHAR(100),
    API_PROVIDER VARCHAR(100),
    API_KEY VARCHAR(255),
    UPDATE_INTERVAL INT,
    UNIT VARCHAR(10),
    FOREIGN KEY (ID_CI_LAYOUT_TYPE) REFERENCES CI_LAYOUT_TYPE(ID_CI_LAYOUT_TYPE)
);

-- Componente de carrossel de imagens
CREATE TABLE CI_COMPONENT_IMAGE_CAROUSEL (
    ID_CI_COMPONENT_IMAGE_CAROUSEL INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_LAYOUT_TYPE INT,
    DURATION_IMAGES INT,
    FOREIGN KEY (ID_CI_LAYOUT_TYPE) REFERENCES CI_LAYOUT_TYPE(ID_CI_LAYOUT_TYPE)
);

-- Imagens pertencentes a um carrossel
CREATE TABLE CI_CAROUSEL_IMAGE (
    ID_CI_CAROUSEL_IMAGE INT AUTO_INCREMENT PRIMARY KEY,
    ID_CI_COMPONENT_IMAGE_CAROUSEL INT,
    IMAGE_URL VARCHAR(255),
    CAPTION VARCHAR(255),
    ORDER_INDEX INT,
    FOREIGN KEY (ID_CI_COMPONENT_IMAGE_CAROUSEL) REFERENCES CI_COMPONENT_IMAGE_CAROUSEL(ID_CI_COMPONENT_IMAGE_CAROUSEL)
);